[DEVX-1673][DEVX-1674][DEVX-1675] Add contributing docs, dangerjs workflow and pull request template
pleo-io/golden-retriever pull request #22
Opened 2023-10-31 17:53 UTC by Niceplace

- Removed dev related instructions from README and added a new CONTRIBUTING.md file with more instructions
- Added missing files to get this service to gold in OpsLevel (contribution guidelines, PR template, dangerJS workflow)

2023-10-31 19:59 UTC, marcos-arranz approved these changes

2023-11-01 16:40 UTC, r0binary requested changes
I agree with Jens the contributing guide is more of a run book

2023-11-02 11:05 UTC, r0binary commented on README.md
> +# Contributing
I like the text you added here @Niceplace. I just a bit confused what we think should go into the contributing guide. For other repos we rely on generic information which is not given here. I think the generic information might best be managed in .github repository to be present in every single repo (we could even delete the OpsLevel check) and more specific information might be added here in a Development section. WDYT?

2023-11-02 11:20 UTC, Niceplace commented on README.md
> +# Contributing
@r0binary My understanding is that Contributing guide === Guide to follow when someone wants to contribute to a repository. So anything relating to the dev setup, how to push code and get it reviewed. I'm also confused because I thought that the agreement was that the CONTRIBUTING.md file was not relevant but a "COntributing" section in the README, which we already have in most repositories but sometimes differently named was OK :/ 

Can you give me a bit more information on what section should I change here ?

2023-11-02 11:51 UTC, VictorPascualV commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Updated tests for modified/added code
```suggestion
- [ ] Added/updated tests for added/modified code
```

2023-11-02 14:35 UTC, r0binary commented on README.md
> +# Contributing
I think no immediate action is required here. It's just that I feel we're putting quite different kind of information in CONTRIBUTING.md for different repos. I believe we should discuss what goes and does not go in there. What we have in there is workflow related information and sometimes technical guidelines. However, we do not state what kind of contributions are welcome for a particular repo. The implicit assumption is people are welcome to create PRs, but it could make sense to point out creating linear issues with ideas, improving documentation or design proposals are (not) welcome for particular repositories

2023-11-02 14:36 UTC, r0binary approved these changes

2023-11-02 14:59 UTC, Niceplace commented on README.md
> +# Contributing
> However, we do not state what kind of contributions are welcome for a particular repo.

That is interesting ! I assumed that contributions in the form of code was implied everywhere but we should definitely discuss what to do with contributing guidelines from a broader perspective.

Will merge this as-is but will come back to it once we reach an agreement. Thanks for the feedback !

2023-11-02 14:59 UTC, merged